CC = g++
# INC = -I./header/controller -I./header/view -I./header/model -I/usr/include/taglib -I/usr/include/SDL2
INC = -I./
# LIB_DIR = /usr/local/lib
# LIB = -L$(LIB_DIR) -ltag -lz -lSDL3
# SRC = ./src/controller/*.cpp
SRC = ./*.cpp
 

all: main

 

main:
	$(CC)  $(INC) -o main $(SRC)
    # $(CC) $(CFLAGS) $(INC) -o main $(SRC) main.cpp $(LIB)